version: '3.3'
services:
  gyant-db:
    image: mongo
    container_name: gyant-db
    volumes:
      - gyantdata:/data/db
    ports:
      - 27017:27017
    networks:
      gyant-net:
        ipv4_address: 174.18.0.100

  gyant-rabbitmq:
    image: rabbitmq:3-management
    container_name: gyant-rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - rabbitmqdata:/var/lib/rabbitmq
    networks:
      gyant-net:
        ipv4_address: 174.18.0.101

  gyant-app:
    build: .
    container_name: gyant-app
    stdin_open: true
    tty: true
    depends_on:
      - gyant-db
      - gyant-rabbitmq
    ports:
      - 8081:3000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      gyant-net:
        ipv4_address: 174.18.0.102
    command: sh -c "cp .env.test.example .env.test && cp .env.development.example .env.development && npm run start:debug"

volumes:
  gyantdata:
  rabbitmqdata:

networks:
  gyant-net:
    ipam:
      config:
        - subnet: 174.18.0.0/24

